"""
analyze_corpus.py
Deep structural analysis of all .md files in 'all docs' for RAG pipeline planning.
"""

import os
import re
import sys
from collections import Counter, defaultdict

sys.stdout.reconfigure(encoding='utf-8')

ALL_DOCS = r'all docs'

# ── Gather all markdown files (including subfolders) ──────────────────────
md_files = []
for root, dirs, files in os.walk(ALL_DOCS):
    for f in files:
        if f.endswith('.md'):
            md_files.append(os.path.join(root, f))
# Also pick up no-extension files that are markdown-like
for f in os.listdir(ALL_DOCS):
    full = os.path.join(ALL_DOCS, f)
    if os.path.isfile(full) and not f.endswith('.md'):
        with open(full, 'rb') as fp:
            snippet = fp.read(200).decode('utf-8', errors='ignore')
        if any(kw in snippet for kw in ['#', '|', '---', '**', '##']):
            md_files.append(full)

md_files = sorted(set(md_files))
print(f"Total files found: {len(md_files)}\n")

# ── Per-file stats ────────────────────────────────────────────────────────
stats = []
all_headings = []
all_boilerplate_hits = []
format_flags = defaultdict(list)  # file -> list of features

HEADING_RE = re.compile(r'^(#{1,6})\s+(.+)', re.MULTILINE)
BULLET_RE  = re.compile(r'^\s*[-*•]\s', re.MULTILINE)
NUM_LIST_RE= re.compile(r'^\s*\d+[.)]\s', re.MULTILINE)
TABLE_RE   = re.compile(r'^\|.+\|', re.MULTILINE)
BOLD_RE    = re.compile(r'\*\*.+?\*\*')
ITALIC_RE  = re.compile(r'(?<!\*)\*[^*\n]+\*(?!\*)')
QA_RE      = re.compile(r'^(Q:|Question:|A:|Answer:)', re.MULTILINE | re.IGNORECASE)
IMG_RE     = re.compile(r'!\[.*?\]\(.*?\)')
LINK_RE    = re.compile(r'(?<!!)\[.*?\]\(.*?\)')
CODE_RE    = re.compile(r'```|`[^`]+`')
TAB_ROW_RE = re.compile(r'^[A-Za-z].+\t.+', re.MULTILINE)  # TSV-style tables (no pipes)
BOILERPLATE= [
    'generated by', 'gpt', 'chatgpt', 'openai', 'timestamp', 'page \d',
    'i\'ll keep this', 'i will', 'because the source', 'let me', 'note:', 'draft',
    'here is', 'this is a', 'as requested', 'sure, here', 'certainly'
]

for fpath in md_files:
    with open(fpath, 'r', encoding='utf-8', errors='ignore') as f:
        text = f.read()

    lines = text.splitlines()
    words = len(text.split())
    # rough token estimate (words * 1.3)
    tokens = int(words * 1.3)
    chars  = len(text)

    headings = HEADING_RE.findall(text)
    heading_levels = Counter(len(h[0]) for h in headings)
    heading_texts  = [h[1][:60] for h in headings]

    has_bullets    = bool(BULLET_RE.search(text))
    has_numlist    = bool(NUM_LIST_RE.search(text))
    has_table_pipe = bool(TABLE_RE.search(text))
    has_table_tsv  = bool(TAB_ROW_RE.search(text))
    has_bold       = bool(BOLD_RE.search(text))
    has_italic     = bool(ITALIC_RE.search(text))
    has_qa         = bool(QA_RE.search(text))
    has_img        = bool(IMG_RE.search(text))
    has_link       = bool(LINK_RE.search(text))
    has_code       = bool(CODE_RE.search(text))

    boilerplate_lines = []
    for i, line in enumerate(lines[:30]):  # check first 30 lines
        for pat in BOILERPLATE:
            if re.search(pat, line, re.IGNORECASE):
                boilerplate_lines.append((i+1, line.strip()))
                break

    # Detect dominant structure type
    if len(headings) > 10:
        struct_type = 'heading-driven outline'
    elif has_table_pipe or has_table_tsv:
        struct_type = 'table-heavy reference'
    elif has_bullets and not headings:
        struct_type = 'flat bullet list'
    elif has_qa:
        struct_type = 'Q&A / exam style'
    else:
        struct_type = 'mixed/prose'

    stats.append({
        'name': os.path.basename(fpath),
        'path': fpath,
        'lines': len(lines),
        'words': words,
        'tokens': tokens,
        'chars': chars,
        'headings': len(headings),
        'heading_levels': dict(heading_levels),
        'heading_texts': heading_texts[:8],
        'has_bullets': has_bullets,
        'has_numlist': has_numlist,
        'has_table_pipe': has_table_pipe,
        'has_table_tsv': has_table_tsv,
        'has_bold': has_bold,
        'has_italic': has_italic,
        'has_qa': has_qa,
        'has_img': has_img,
        'has_code': has_code,
        'struct_type': struct_type,
        'boilerplate': boilerplate_lines,
        'text_snippet': text[:1200],
    })
    all_headings.extend(heading_texts)

# ── Report ────────────────────────────────────────────────────────────────
print("=" * 80)
print("  CORPUS STRUCTURAL ANALYSIS REPORT")
print("  FCPS / MRCOG O&G Markdown Notes — RAG Pipeline Planning")
print("=" * 80)

# ─ 0. File inventory ─────────────────────────────────────────────────────
print("\n## 0. FILE INVENTORY\n")
for i, s in enumerate(stats, 1):
    loc = '(new docs)' if 'new docs' in s['path'] else '(all docs)'
    print(f"  {i:2}. [{loc}] {s['name'][:70]}")
    print(f"       Lines={s['lines']:>5} | Words={s['words']:>6} | ~Tokens={s['tokens']:>7} | Headings={s['headings']:>4} | Type={s['struct_type']}")

# ─ 1. Heading structure ───────────────────────────────────────────────────
print("\n\n## 1. HEADING STRUCTURE\n")
level_total = Counter()
for s in stats:
    for lvl, cnt in s['heading_levels'].items():
        level_total[lvl] += cnt

print("Heading levels across corpus:")
for lvl in sorted(level_total):
    print(f"  H{lvl} (#{lvl*'#'[:0]}): {level_total[lvl]} total occurrences")

print("\nPer-file heading breakdown:")
for s in stats:
    lvls = ', '.join(f'H{k}={v}' for k, v in sorted(s['heading_levels'].items()))
    print(f"  {s['name'][:55]:<56} | {lvls or 'NO HEADINGS'}")

# Sample heading texts
print("\nSample heading texts (first 6 per file, first 10 files):")
for s in stats[:10]:
    print(f"\n  [{s['name'][:50]}]")
    for h in s['heading_texts'][:6]:
        print(f"    • {h}")

# ─ 2. Formatting patterns ────────────────────────────────────────────────
print("\n\n## 2. CONTENT FORMATTING PATTERNS\n")
print(f"{'File':<56} | Bullets | NumList | TblPipe | TblTSV | Bold | Italic | Q&A | Img | Code")
print("-"*120)
for s in stats:
    def b(v): return '  ✓  ' if v else '  ✗  '
    print(f"{s['name'][:55]:<56} | {b(s['has_bullets'])} | {b(s['has_numlist'])} | {b(s['has_table_pipe'])} | {b(s['has_table_tsv'])} | {b(s['has_bold'])} | {b(s['has_italic'])} | {b(s['has_qa'])} | {b(s['has_img'])} | {b(s['has_code'])}")

# ─ 3. Structural consistency / types ─────────────────────────────────────
print("\n\n## 3. STRUCTURAL CONSISTENCY\n")
type_counts = Counter(s['struct_type'] for s in stats)
print("Structure type distribution:")
for stype, cnt in type_counts.most_common():
    print(f"  {stype}: {cnt} files")

print("\n\n### 3a. REPRESENTATIVE FILE SNIPPETS (first 80 lines each)\n")
# Pick 3 representative files of different types
shown_types = set()
shown = []
for s in stats:
    if s['struct_type'] not in shown_types:
        shown.append(s)
        shown_types.add(s['struct_type'])
    if len(shown) >= 3:
        break

for s in shown:
    print(f"\n{'='*60}")
    print(f"FILE: {s['name']}")
    print(f"TYPE: {s['struct_type']} | Lines={s['lines']} | Words={s['words']}")
    print(f"{'='*60}")
    with open(s['path'], 'r', encoding='utf-8', errors='ignore') as f:
        snippet_lines = f.readlines()[:80]
    print(''.join(snippet_lines))

# ─ 4. Noise / boilerplate ────────────────────────────────────────────────
print("\n\n## 4. NOISE AND CLEANUP CANDIDATES\n")
for s in stats:
    if s['boilerplate']:
        print(f"\n  [{s['name'][:55]}] — boilerplate hits:")
        for lineno, line in s['boilerplate']:
            print(f"    Line {lineno:3}: {line[:100]}")

# Check for near-duplicate file names
print("\nPotentially duplicate/overlapping files:")
names_lower = [s['name'].lower() for s in stats]
for i, s in enumerate(stats):
    for j, t in enumerate(stats):
        if i >= j: continue
        # Simple overlap: one name contains key words of another
        words_i = set(s['name'].lower().replace('.md','').split())
        words_j = set(t['name'].lower().replace('.md','').split())
        overlap = words_i & words_j - {'and','in','of','the','a','for','to'}
        if len(overlap) >= 4:
            print(f"  Possible overlap ({len(overlap)} shared words):")
            print(f"    → {s['name']}")
            print(f"    → {t['name']}")
            print(f"    Shared: {overlap}")

# ─ 5. Size & density stats ───────────────────────────────────────────────
print("\n\n## 5. SIZE AND DENSITY STATS\n")
all_words  = [s['words']  for s in stats]
all_tokens = [s['tokens'] for s in stats]
all_lines  = [s['lines']  for s in stats]

def stat_row(label, vals):
    vals_sorted = sorted(vals)
    n = len(vals_sorted)
    median = vals_sorted[n//2]
    avg = int(sum(vals_sorted)/n)
    return f"  {label:<12}: min={min(vals_sorted):>7,} | max={max(vals_sorted):>7,} | median={median:>7,} | avg={avg:>7,}"

print(stat_row("Lines", all_lines))
print(stat_row("Words", all_words))
print(stat_row("~Tokens", all_tokens))

print("\nTop 5 largest files (by words):")
for s in sorted(stats, key=lambda x: -x['words'])[:5]:
    print(f"  {s['words']:>7,} words | {s['lines']:>5} lines | {s['name'][:65]}")

print("\nTop 5 smallest files (by words):")
for s in sorted(stats, key=lambda x: x['words'])[:5]:
    print(f"  {s['words']:>7,} words | {s['lines']:>5} lines | {s['name'][:65]}")

# ─ 6. Semantic unit hints ─────────────────────────────────────────────────
print("\n\n## 6. SEMANTIC UNIT HINTS\n")
print("Heading density (headings per 100 lines):")
for s in sorted(stats, key=lambda x: -(x['headings']/(x['lines']+1)*100)):
    density = s['headings'] / (s['lines'] + 1) * 100
    print(f"  {density:5.1f} h/100L | {s['headings']:>4} headings | {s['lines']:>5} lines | {s['name'][:60]}")

# Show example atomic units from 3 files
print("\n### Example 'atomic knowledge units' from 3 representative files:\n")
for s in shown[:3]:
    print(f"\n--- {s['name']} ---")
    with open(s['path'], 'r', encoding='utf-8', errors='ignore') as f:
        text = f.read()
    # Extract first 3 heading-bounded sections
    sections = re.split(r'\n(?=#{1,3} )', text)
    for sec in sections[1:4]:
        lines_in_sec = sec.strip().splitlines()
        print(f"\n  [SECTION | {len(lines_in_sec)} lines]")
        for l in lines_in_sec[:12]:
            print(f"  {l}")
        if len(lines_in_sec) > 12:
            print(f"  ... (+{len(lines_in_sec)-12} more lines)")

print("\n\n## END OF REPORT")
